// club-signing.js — mode ?sign=club : contre-signature à distance du dossier reçu
// Chargé par yce_form_filler.html ; scripts classiques partageant la portée globale.
"use strict";
// -------------------- mode signature du président de club --------------------
const COMMIT_FILE={buf:null,name:null};
function loadCommitFile(inp){
  const file=inp.files[0];if(!file)return;
  const r=new FileReader();
  r.onload=function(){COMMIT_FILE.buf=r.result;COMMIT_FILE.name=file.name;
    const lbl=document.getElementById("commitfile-lbl");
    if(lbl)lbl.textContent="✔ "+file.name;
    setStatus("Commitment loaded: "+file.name,false);};
  r.readAsArrayBuffer(file);
}
async function signCommitmentFile(){
  const entries=await unzip(COMMIT_FILE.buf);
  const td=new TextDecoder(),te=new TextEncoder();
  const docE=entries.find(function(e){return e.name==="word/document.xml";});
  const relE=entries.find(function(e){return e.name==="word/_rels/document.xml.rels";});
  if(!docE||!relE)throw new Error("invalid Commitment document");
  let doc=td.decode(docE.data);
  const bm=doc.match(/<w:bookmarkStart w:id="\d+" w:name="SIGSLOT_CLUB"\/><w:bookmarkEnd w:id="\d+"\/>/);
  if(!bm)throw new Error("no club signature slot found in this Commitment (already signed, or generated by an old version)");
  entries.push({name:"word/media/rIdSigClub.png",data:dataUrlToBytes(SIGS.club.cv.toDataURL("image/png"))});
  relE.data=te.encode(td.decode(relE.data).replace("</Relationships>",'<Relationship Id="rIdSigClub" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/rIdSigClub.png"/></Relationships>'));
  doc=doc.replace(bm[0],docxSigRun("rIdSigClub",910));
  docE.data=te.encode(doc);
  return await buildZip(entries,"application/vnd.openxmlformats-officedocument.wordprocessingml.document");
}
